sudo: false

language: node_js

env:
  global:
    - secure: ewlU1jjDXKiFfgNqNfxJiMee0+eIJVP87aJmu1vbqTEubE2ibxZkdu5o3LJXbVkRVZreM0obYmxDpdZQD7SOx29bkxyeqCwTn70FOnmQgd0y9BdHcuKCLFidHRIY78mlb2d40l0XeZHhwgwo+pXFY/j5uh1v2z/sTcaH5yosuDQ=
    - secure: ARIikFoe3Q8YZgqgtAAuKhLFNZA38lcq8BOFzrl8KhOv6eAvvE3HQp2opYWAOQCvzHRzFbh3mdqnC6PXnybSOygI7bRv7T81iVjyk2JDlK8gR1+ElswQv4TG/xlEPIoR/bN30IsCnCayz9RwcWhl5fnetYlXG+bX6FQd43uYNkY=

matrix:
  include:
    - node_js: "0.10"
    - node_js: "0.12"
    - node_js: "0.10"
      env: BROWSER=1
